/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import clases.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import static ventanas.Compras.*;

/**
 *
 * @author Misael Villar Julian
 */
public class BuscarProveedor extends javax.swing.JFrame {

    boolean opcionClick = false;
    int bus = 0;

    public BuscarProveedor() {
        initComponents();

        setSize(335, 580);
        setLocationRelativeTo(null);
        CargarDatosTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanelBuscarCliente = new javax.swing.JPanel();
        JLPestañaBuscar = new javax.swing.JLabel();
        JBSalirBPrv = new javax.swing.JButton();
        JLPestañaTitulo = new javax.swing.JLabel();
        JLBanner = new javax.swing.JLabel();
        JScrollPaneProveedor = new javax.swing.JScrollPane();
        JTableBuscarProveedor = new javax.swing.JTable();
        JLOrdenarPorProvForm = new javax.swing.JLabel();
        JTFOrdenarPorProvForm = new javax.swing.JTextField();
        JBRegistrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        JPanelBuscarCliente.setBackground(new java.awt.Color(236, 236, 236));
        JPanelBuscarCliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLPestañaBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Buscar/Buscar Proveedor.png"))); // NOI18N
        JPanelBuscarCliente.add(JLPestañaBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 130, -1));

        JBSalirBPrv.setText("Salir");
        JBSalirBPrv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBSalirBPrvActionPerformed(evt);
            }
        });
        JPanelBuscarCliente.add(JBSalirBPrv, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        JLPestañaTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Buscar/PestañaBuscar.png"))); // NOI18N
        JPanelBuscarCliente.add(JLPestañaTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        JLBanner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Buscar/BannerBuscar.png"))); // NOI18N
        JPanelBuscarCliente.add(JLBanner, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        JTableBuscarProveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Código", "Descripción"
            }
        ));
        JTableBuscarProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTableBuscarProveedorMouseClicked(evt);
            }
        });
        JScrollPaneProveedor.setViewportView(JTableBuscarProveedor);

        JPanelBuscarCliente.add(JScrollPaneProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 300, 430));

        JLOrdenarPorProvForm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Buscar/BuscarPorProv.png"))); // NOI18N
        JPanelBuscarCliente.add(JLOrdenarPorProvForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, 20));

        JTFOrdenarPorProvForm.setBackground(new java.awt.Color(236, 236, 236));
        JTFOrdenarPorProvForm.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        JTFOrdenarPorProvForm.setBorder(null);
        JTFOrdenarPorProvForm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JTFOrdenarPorProvFormKeyReleased(evt);
            }
        });
        JPanelBuscarCliente.add(JTFOrdenarPorProvForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 120, -1));

        JBRegistrar.setText("Registrar");
        JBRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBRegistrarActionPerformed(evt);
            }
        });
        JPanelBuscarCliente.add(JBRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanelBuscarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanelBuscarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBRegistrarActionPerformed
        // TODO add your handling code here:
        new Proveedores().setVisible(true);
    }//GEN-LAST:event_JBRegistrarActionPerformed

    private void JTFOrdenarPorProvFormKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTFOrdenarPorProvFormKeyReleased
        // TODO add your handling code here:
        BusquedaTiempoReal();
    }//GEN-LAST:event_JTFOrdenarPorProvFormKeyReleased

    private void JTableBuscarProveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTableBuscarProveedorMouseClicked
        // TODO add your handling code here:
        int fila = JTableBuscarProveedor.getSelectedRow();
        bus = Integer.parseInt(JTableBuscarProveedor.getValueAt(fila, 0).toString());
        opcionClick = true;
        try {

            Connection cn = Conexion.conectar();
            PreparedStatement ps = cn.prepareStatement("SELECT id_proveedor, descripcion_proveedor FROM proveedor WHERE id_proveedor=" + bus);
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                JTextCodigoProveedorComForm.setText(rs.getString("id_proveedor"));
                JTextProveedorComForm.setText(rs.getString("descripcion_proveedor"));
            }
        } catch (SQLException ex) {
            System.out.println(ex.toString());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(RegistrarProducto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_JTableBuscarProveedorMouseClicked

    private void JBSalirBPrvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBSalirBPrvActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_JBSalirBPrvActionPerformed

    private void CargarDatosTabla() {
        try {
            DefaultTableModel modelo = new DefaultTableModel();
            modelo.addColumn("Codigo");
            modelo.addColumn("Descripcion");
            JTableBuscarProveedor.setModel(modelo);

            Connection cn = Conexion.conectar();
            Statement st = cn.createStatement();

            String sql = "SELECT id_proveedor, descripcion_proveedor FROM proveedor;";

            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                Object[] filas = new Object[2];
                for (int i = 0; i < 2; i++) {
                    filas[i] = rs.getObject(i + 1);
                }
                modelo.addRow(filas);
            }

        } catch (SQLException ex) {
            System.err.println(ex.toString());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(RegistrarProducto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void BusquedaTiempoReal() {
        try {
            DefaultTableModel modelo = new DefaultTableModel();
            modelo.addColumn("Codigo");
            modelo.addColumn("Descripcion");
            JTableBuscarProveedor.setModel(modelo);

            Connection cn = Conexion.conectar();
            Statement st = cn.createStatement();

            String sql = "SELECT id_proveedor, descripcion_proveedor FROM proveedor WHERE "
                    + "id_proveedor LIKE '%" + JTFOrdenarPorProvForm.getText().trim() + "%' "
                    + "OR "
                    + "descripcion_proveedor LIKE '%" + JTFOrdenarPorProvForm.getText().trim() + "%';";
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                Object[] filas = new Object[2];
                for (int i = 0; i < 2; i++) {
                    filas[i] = rs.getObject(i + 1);
                    System.out.println("" + filas[i]);
                }
                modelo.addRow(filas);
            }

        } catch (SQLException ex) {
            System.err.println(ex.toString());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(RegistrarProducto.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new BuscarProveedor().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBRegistrar;
    private javax.swing.JButton JBSalirBPrv;
    private javax.swing.JLabel JLBanner;
    private javax.swing.JLabel JLOrdenarPorProvForm;
    private javax.swing.JLabel JLPestañaBuscar;
    private javax.swing.JLabel JLPestañaTitulo;
    private javax.swing.JPanel JPanelBuscarCliente;
    private javax.swing.JScrollPane JScrollPaneProveedor;
    private javax.swing.JTextField JTFOrdenarPorProvForm;
    private javax.swing.JTable JTableBuscarProveedor;
    // End of variables declaration//GEN-END:variables
}
