/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import clases.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import static ventanas.ApartadoAbonos.*;
import static ventanas.Compras.*;
import static ventanas.Ventas.*;

/**
 *
 * @author Misael Villar Julian
 */
public class BuscarProducto extends javax.swing.JFrame {

    long bus = 0;

    public BuscarProducto() {
        initComponents();

        setSize(335, 580);
        setLocationRelativeTo(null);
        CargarDatosTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanelBuscarCliente = new javax.swing.JPanel();
        JLPestañaBuscar = new javax.swing.JLabel();
        JBSalirBP = new javax.swing.JButton();
        JLPestañaTitulo = new javax.swing.JLabel();
        JLBanner = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTableBuscarProducto = new javax.swing.JTable();
        JLOrdenarPorProForm = new javax.swing.JLabel();
        JTFOrdenarPorProdForm = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        JPanelBuscarCliente.setBackground(new java.awt.Color(236, 236, 236));
        JPanelBuscarCliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLPestañaBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Buscar/Buscar Producto.png"))); // NOI18N
        JPanelBuscarCliente.add(JLPestañaBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        JBSalirBP.setText("Salir");
        JBSalirBP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBSalirBPActionPerformed(evt);
            }
        });
        JPanelBuscarCliente.add(JBSalirBP, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        JLPestañaTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Buscar/PestañaBuscar.png"))); // NOI18N
        JPanelBuscarCliente.add(JLPestañaTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        JLBanner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Buscar/BannerBuscar.png"))); // NOI18N
        JPanelBuscarCliente.add(JLBanner, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        JTableBuscarProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Código", "Descripción", "Stock"
            }
        ));
        JTableBuscarProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTableBuscarProductoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTableBuscarProducto);

        JPanelBuscarCliente.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 300, 430));

        JLOrdenarPorProForm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Buscar/BuscarPorPro.png"))); // NOI18N
        JPanelBuscarCliente.add(JLOrdenarPorProForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, 20));

        JTFOrdenarPorProdForm.setBackground(new java.awt.Color(236, 236, 236));
        JTFOrdenarPorProdForm.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        JTFOrdenarPorProdForm.setBorder(null);
        JTFOrdenarPorProdForm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JTFOrdenarPorProdFormKeyReleased(evt);
            }
        });
        JPanelBuscarCliente.add(JTFOrdenarPorProdForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 120, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanelBuscarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanelBuscarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTFOrdenarPorProdFormKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTFOrdenarPorProdFormKeyReleased
        // TODO add your handling code here:
        BusquedaTiempoReal();
    }//GEN-LAST:event_JTFOrdenarPorProdFormKeyReleased

    private void JBSalirBPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBSalirBPActionPerformed
        // TODO add your handling code here:
        apartado = false;
        compra = false;
        venta = false;
        dispose();
    }//GEN-LAST:event_JBSalirBPActionPerformed

    private void JTableBuscarProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTableBuscarProductoMouseClicked
        // TODO add your handling code here:
        int fila = JTableBuscarProducto.getSelectedRow();
        bus = Long.parseLong(JTableBuscarProducto.getValueAt(fila, 0).toString());

        try {

            Connection cn = Conexion.conectar();
            PreparedStatement ps = cn.prepareStatement("SELECT * FROM producto WHERE id_producto=" + bus + "");
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                if (venta == true) {
                    JTextCodigoProductoVenForm.setText(rs.getString("id_producto"));
                    JTextDescripcionProdVenForm.setText(rs.getString("descripcion_producto"));
                    categoriaven = rs.getString("categoria_producto");
                    JTextStockVenForm.setText(rs.getString("Stock_producto"));
                    JTextPrecioVentaVenForm.setText(rs.getString("precio_producto"));

                } else if (compra == true) {
                    JTextCodigoProductoComForm.setText(rs.getString("id_producto"));
                    descripcionprod = rs.getString("descripcion_producto");
                    categoriaprod = rs.getString("categoria_producto");
                    JTextCantidadComForm.setText(rs.getString("Stock_producto"));
                    JTextPrecioVentaComForm.setText(rs.getString("precio_producto"));

                } else if (apartado == true) {
                    JTextCodigoProductoAAForm.setText(rs.getString("id_producto"));
                    JTextDescripcionProdAAForm.setText(rs.getString("descripcion_producto"));
                    JTextStockAAForm.setText(rs.getString("Stock_producto"));
                    JTextPrecioVentaAAForm.setText(rs.getString("precio_producto"));
                }
            }
        } catch (SQLException ex) {
            System.out.println(ex.toString());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(RegistrarProducto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_JTableBuscarProductoMouseClicked

    private void CargarDatosTabla() {
        try {
            DefaultTableModel modelo = new DefaultTableModel();
            modelo.addColumn("Codigo");
            modelo.addColumn("Descripcion");
            modelo.addColumn("Stock");
            JTableBuscarProducto.setModel(modelo);

            Connection cn = Conexion.conectar();
            Statement st = cn.createStatement();

            String sql = "SELECT id_producto, descripcion_producto, Stock_producto FROM producto;";

            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                Object[] filas = new Object[3];
                for (int i = 0; i < 3; i++) {
                    filas[i] = rs.getObject(i + 1);
                }
                modelo.addRow(filas);
            }

        } catch (SQLException ex) {
            System.err.println(ex.toString());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(RegistrarProducto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void BusquedaTiempoReal() {
        try {
            DefaultTableModel modelo = new DefaultTableModel();
            modelo.addColumn("Codigo");
            modelo.addColumn("Descripcion");
            modelo.addColumn("Stock");
            
            JTableBuscarProducto.setModel(modelo);

            Connection cn = Conexion.conectar();
            Statement st = cn.createStatement();

            String sql = "SELECT id_producto, descripcion_producto, Stock_producto FROM producto WHERE "
                    + "id_producto LIKE '%" + JTFOrdenarPorProdForm.getText().trim() + "%' "
                    + "OR "
                    + "descripcion_producto LIKE '%" + JTFOrdenarPorProdForm.getText().trim() + "%';";
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                Object[] filas = new Object[3];
                for (int i = 0; i < 3; i++) {
                    filas[i] = rs.getObject(i + 1);
                }
                modelo.addRow(filas);
            }

        } catch (SQLException ex) {
            System.err.println(ex.toString());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(RegistrarProducto.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new BuscarProducto().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBSalirBP;
    private javax.swing.JLabel JLBanner;
    private javax.swing.JLabel JLOrdenarPorProForm;
    private javax.swing.JLabel JLPestañaBuscar;
    private javax.swing.JLabel JLPestañaTitulo;
    private javax.swing.JPanel JPanelBuscarCliente;
    private javax.swing.JTextField JTFOrdenarPorProdForm;
    private javax.swing.JTable JTableBuscarProducto;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
