/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import javax.swing.JOptionPane;
import static ventanas.Ventas.*;

/**
 *
 * @author Misael Villar Julian
 */
public class CobrarVenta extends javax.swing.JFrame {

    /**
     * Creates new form CobrarVenta
     */
    public CobrarVenta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanelCobrar = new javax.swing.JPanel();
        JLTitulo = new javax.swing.JLabel();
        JButtonSalir = new javax.swing.JButton();
        JLPestañaCobrar = new javax.swing.JLabel();
        JLBanner = new javax.swing.JLabel();
        JLPagoCon = new javax.swing.JLabel();
        JLLineaCobrar = new javax.swing.JLabel();
        JBTerminarVenta = new javax.swing.JButton();
        JLProCambio = new javax.swing.JLabel();
        JLProductoAPaga = new javax.swing.JLabel();
        JLProductoAPagar = new javax.swing.JLabel();
        JLDetalleCompra = new javax.swing.JLabel();
        JLProductosAPagar = new javax.swing.JLabel();
        JLLineasProductoAPagar = new javax.swing.JLabel();
        JLLineaPaga = new javax.swing.JLabel();
        JLPaga = new javax.swing.JLabel();
        JLCambio = new javax.swing.JLabel();
        JLLineaCambio = new javax.swing.JLabel();
        JLAreaCobrar = new javax.swing.JLabel();
        JTextFEntradaPago = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        JPanelCobrar.setBackground(new java.awt.Color(236, 236, 236));
        JPanelCobrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenventa/CobrarTitulo.png"))); // NOI18N
        JPanelCobrar.add(JLTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

        JButtonSalir.setText("Salir");
        JButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonSalirActionPerformed(evt);
            }
        });
        JPanelCobrar.add(JButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, -1, -1));

        JLPestañaCobrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenventa/PestañaCobrar.png"))); // NOI18N
        JPanelCobrar.add(JLPestañaCobrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        JLBanner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenventa/BannerVenta.png"))); // NOI18N
        JPanelCobrar.add(JLBanner, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, -1));

        JLPagoCon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenventa/Pago Con.png"))); // NOI18N
        JPanelCobrar.add(JLPagoCon, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, -1));

        JLLineaCobrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenventa/LineaCobrar.png"))); // NOI18N
        JPanelCobrar.add(JLLineaCobrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        JBTerminarVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenventa/Cobrar_1.png"))); // NOI18N
        JBTerminarVenta.setBorder(null);
        JBTerminarVenta.setBorderPainted(false);
        JBTerminarVenta.setContentAreaFilled(false);
        JBTerminarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTerminarVentaActionPerformed(evt);
            }
        });
        JPanelCobrar.add(JBTerminarVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 230, -1));

        JLProCambio.setBackground(new java.awt.Color(236, 236, 236));
        JLProCambio.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        JLProCambio.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        JPanelCobrar.add(JLProCambio, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 330, 100, 20));

        JLProductoAPaga.setBackground(new java.awt.Color(236, 236, 236));
        JLProductoAPaga.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        JLProductoAPaga.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        JPanelCobrar.add(JLProductoAPaga, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, 100, 20));

        JLProductoAPagar.setBackground(new java.awt.Color(236, 236, 236));
        JLProductoAPagar.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        JLProductoAPagar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        JPanelCobrar.add(JLProductoAPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, 70, 20));

        JLDetalleCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenventa/Detalles de la Compra.png"))); // NOI18N
        JPanelCobrar.add(JLDetalleCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, -1, -1));

        JLProductosAPagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenventa/Productos A Pagar.png"))); // NOI18N
        JPanelCobrar.add(JLProductosAPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, -1, -1));

        JLLineasProductoAPagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenventa/LineaProductoPagar.png"))); // NOI18N
        JPanelCobrar.add(JLLineasProductoAPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, -1, -1));

        JLLineaPaga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenventa/LineaPaga.png"))); // NOI18N
        JPanelCobrar.add(JLLineaPaga, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, -1, -1));

        JLPaga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenventa/Paga.png"))); // NOI18N
        JPanelCobrar.add(JLPaga, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, -1, -1));

        JLCambio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenventa/Cambio.png"))); // NOI18N
        JPanelCobrar.add(JLCambio, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, -1, -1));

        JLLineaCambio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenventa/LineaCambio.png"))); // NOI18N
        JPanelCobrar.add(JLLineaCambio, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, -1, -1));

        JLAreaCobrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenventa/DetalleCompra.png"))); // NOI18N
        JPanelCobrar.add(JLAreaCobrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, -1, -1));

        JTextFEntradaPago.setBackground(new java.awt.Color(236, 236, 236));
        JTextFEntradaPago.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        JTextFEntradaPago.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTextFEntradaPago.setBorder(null);
        JTextFEntradaPago.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JTextFEntradaPagoKeyReleased(evt);
            }
        });
        JPanelCobrar.add(JTextFEntradaPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 220, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanelCobrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanelCobrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_JButtonSalirActionPerformed

    private void JBTerminarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTerminarVentaActionPerformed
        // TODO add your handling code here:
        JLProductoAPagar.setText(String.valueOf(totalventa));
        float cambio = 0;
        float importe = Float.parseFloat(JTextFEntradaPago.getText().trim());
        if (importe <= 0 || totalventa <= 0) {
            JOptionPane.showMessageDialog(null, "Operacion Invalida!!");
        } else {
            JLProductoAPaga.setText(String.valueOf(importe));
            if (cambio <= 0) {
                cambio = (totalventa - importe) * -1;
                JLProCambio.setText(String.valueOf(cambio));
                JLResultadoCambioVen.setText(String.valueOf(cambio));
            } else {
                cambio = totalventa - importe;
                JLProCambio.setText(String.valueOf(cambio));
                JLResultadoCambioVen.setText(String.valueOf(cambio));
            }

        }

    }//GEN-LAST:event_JBTerminarVentaActionPerformed

    private void JTextFEntradaPagoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTextFEntradaPagoKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_JTextFEntradaPagoKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CobrarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CobrarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CobrarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CobrarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new CobrarVenta().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBTerminarVenta;
    private javax.swing.JButton JButtonSalir;
    private javax.swing.JLabel JLAreaCobrar;
    private javax.swing.JLabel JLBanner;
    private javax.swing.JLabel JLCambio;
    private javax.swing.JLabel JLDetalleCompra;
    private javax.swing.JLabel JLLineaCambio;
    private javax.swing.JLabel JLLineaCobrar;
    private javax.swing.JLabel JLLineaPaga;
    private javax.swing.JLabel JLLineasProductoAPagar;
    private javax.swing.JLabel JLPaga;
    private javax.swing.JLabel JLPagoCon;
    private javax.swing.JLabel JLPestañaCobrar;
    public static javax.swing.JLabel JLProCambio;
    public static javax.swing.JLabel JLProductoAPaga;
    public static javax.swing.JLabel JLProductoAPagar;
    private javax.swing.JLabel JLProductosAPagar;
    private javax.swing.JLabel JLTitulo;
    private javax.swing.JPanel JPanelCobrar;
    private javax.swing.JTextField JTextFEntradaPago;
    // End of variables declaration//GEN-END:variables
}
