package ventanas;

import clases.Conexion;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Misael Villar Julian
 */
public class Configuracion extends javax.swing.JFrame {

    boolean opcionClick = false;
    int bus = 0;
    public static String tipoAcceso = "";

    public Configuracion() {
        initComponents();

        setLocationRelativeTo(null);
        CargarDatosTabla();
        SeleccionAdministrador();
        SeleccionEmpleado();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JTabbedPane = new javax.swing.JTabbedPane();
        JPanelUsuario = new javax.swing.JPanel();
        JLabelTitulo = new javax.swing.JLabel();
        JButtonSalir = new javax.swing.JButton();
        JLabelBanner = new javax.swing.JLabel();
        JLNombreCompleto = new javax.swing.JLabel();
        JLNomCompForm = new javax.swing.JLabel();
        JTextNomCompForm = new javax.swing.JTextField();
        JLUsuario = new javax.swing.JLabel();
        JLUsuarioForm = new javax.swing.JLabel();
        JTextUsuarioForm = new javax.swing.JTextField();
        JLContrasena = new javax.swing.JLabel();
        JLContrasenaForm = new javax.swing.JLabel();
        JTextContrasenaForm = new javax.swing.JTextField();
        JLConfirmarContra = new javax.swing.JLabel();
        JLConfirmarContraForm = new javax.swing.JLabel();
        JTextConfirmarContraForm = new javax.swing.JTextField();
        JLFechaNacimiento = new javax.swing.JLabel();
        JLFechaNacimForm = new javax.swing.JLabel();
        JTextFechaNacimForm = new javax.swing.JTextField();
        JLRol = new javax.swing.JLabel();
        JComboBoxRol = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTableAreaUsuario = new javax.swing.JTable();
        JButtonGuardar = new javax.swing.JButton();
        JButtonEliminar = new javax.swing.JButton();
        JButtonLimpiar = new javax.swing.JButton();
        JPanelPrivilegio = new javax.swing.JPanel();
        JLTituloBanner = new javax.swing.JLabel();
        JLBanner = new javax.swing.JLabel();
        JCheckBoxApartadoAbono = new javax.swing.JCheckBox();
        JLApartado = new javax.swing.JLabel();
        JCheckBoxCompras = new javax.swing.JCheckBox();
        JLCompras = new javax.swing.JLabel();
        JCheckBoxConfiguracion = new javax.swing.JCheckBox();
        JLConfig = new javax.swing.JLabel();
        JCheckBoxCorteCaja = new javax.swing.JCheckBox();
        JLCorte = new javax.swing.JLabel();
        JCheckBoxInventario = new javax.swing.JCheckBox();
        JLInvent = new javax.swing.JLabel();
        JCheckBoxProveedores = new javax.swing.JCheckBox();
        JLProveedor = new javax.swing.JLabel();
        JCheckBoxRegCliente = new javax.swing.JCheckBox();
        JLRegClientes = new javax.swing.JLabel();
        JCheckBoxRegProducto = new javax.swing.JCheckBox();
        JLRegProduct = new javax.swing.JLabel();
        JCheckBoxVentas = new javax.swing.JCheckBox();
        JLVentas = new javax.swing.JLabel();
        JCheckBoxApartadoAbono1 = new javax.swing.JCheckBox();
        JLApartado1 = new javax.swing.JLabel();
        JCheckBoxCompras1 = new javax.swing.JCheckBox();
        JLCompras1 = new javax.swing.JLabel();
        JCheckBoxConfiguracion1 = new javax.swing.JCheckBox();
        JLConfig1 = new javax.swing.JLabel();
        JCheckBoxCorteCaja1 = new javax.swing.JCheckBox();
        JLCorte1 = new javax.swing.JLabel();
        JCheckBoxInventario1 = new javax.swing.JCheckBox();
        JLInvent1 = new javax.swing.JLabel();
        JCheckBoxProveedores1 = new javax.swing.JCheckBox();
        JLProveedor1 = new javax.swing.JLabel();
        JCheckBoxRegCliente1 = new javax.swing.JCheckBox();
        JLRegClientes1 = new javax.swing.JLabel();
        JCheckBoxRegProducto1 = new javax.swing.JCheckBox();
        JLRegProduct1 = new javax.swing.JLabel();
        JCheckBoxVentas1 = new javax.swing.JCheckBox();
        JButtonGuardarA = new javax.swing.JButton();
        JButtonGuardarE = new javax.swing.JButton();
        JLVentas1 = new javax.swing.JLabel();
        JLTituloCuadroADM = new javax.swing.JLabel();
        JLTituloCuadroEMP = new javax.swing.JLabel();
        JLCuadroAdm = new javax.swing.JLabel();
        JLCuadroEmp = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        JPanelUsuario.setBackground(new java.awt.Color(236, 236, 236));
        JPanelUsuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLabelTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenusuario/Configuración.png"))); // NOI18N
        JPanelUsuario.add(JLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, -1, -1));

        JButtonSalir.setText("Salir");
        JButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonSalirActionPerformed(evt);
            }
        });
        JPanelUsuario.add(JButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 20, -1, -1));

        JLabelBanner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenusuario/Banner.png"))); // NOI18N
        JPanelUsuario.add(JLabelBanner, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 60));

        JLNombreCompleto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenusuario/Nombre Completo.png"))); // NOI18N
        JPanelUsuario.add(JLNombreCompleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        JLNomCompForm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenusuario/NombreCompleto.png"))); // NOI18N
        JPanelUsuario.add(JLNomCompForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        JTextNomCompForm.setBackground(new java.awt.Color(236, 236, 236));
        JTextNomCompForm.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        JTextNomCompForm.setBorder(null);
        JPanelUsuario.add(JTextNomCompForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 190, -1));

        JLUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenusuario/Usuario.png"))); // NOI18N
        JPanelUsuario.add(JLUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, 10));

        JLUsuarioForm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenusuario/UsuarioCampo.png"))); // NOI18N
        JPanelUsuario.add(JLUsuarioForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        JTextUsuarioForm.setBackground(new java.awt.Color(236, 236, 236));
        JTextUsuarioForm.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        JTextUsuarioForm.setBorder(null);
        JPanelUsuario.add(JTextUsuarioForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 190, -1));

        JLContrasena.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenusuario/Contraseña.png"))); // NOI18N
        JPanelUsuario.add(JLContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        JLContrasenaForm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenusuario/ContrasenaCampo.png"))); // NOI18N
        JPanelUsuario.add(JLContrasenaForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        JTextContrasenaForm.setBackground(new java.awt.Color(236, 236, 236));
        JTextContrasenaForm.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        JTextContrasenaForm.setBorder(null);
        JPanelUsuario.add(JTextContrasenaForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 190, -1));

        JLConfirmarContra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenusuario/Confirmar Contraseña.png"))); // NOI18N
        JPanelUsuario.add(JLConfirmarContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        JLConfirmarContraForm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenusuario/ConfirmarContraCampo.png"))); // NOI18N
        JPanelUsuario.add(JLConfirmarContraForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        JTextConfirmarContraForm.setBackground(new java.awt.Color(236, 236, 236));
        JTextConfirmarContraForm.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        JTextConfirmarContraForm.setBorder(null);
        JPanelUsuario.add(JTextConfirmarContraForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 190, -1));

        JLFechaNacimiento.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JLFechaNacimiento.setForeground(new java.awt.Color(0, 0, 0));
        JLFechaNacimiento.setText("Fecha de Nacimiento:");
        JPanelUsuario.add(JLFechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        JLFechaNacimForm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenusuario/ConfirmarContraCampo.png"))); // NOI18N
        JPanelUsuario.add(JLFechaNacimForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        JTextFechaNacimForm.setBackground(new java.awt.Color(236, 236, 236));
        JTextFechaNacimForm.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        JTextFechaNacimForm.setText("YY-MM-DD");
        JTextFechaNacimForm.setBorder(null);
        JPanelUsuario.add(JTextFechaNacimForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 190, -1));

        JLRol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenusuario/Rol.png"))); // NOI18N
        JPanelUsuario.add(JLRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, 10));

        JComboBoxRol.setBackground(new java.awt.Color(236, 236, 236));
        JComboBoxRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Empleado" }));
        JComboBoxRol.setBorder(null);
        JComboBoxRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JComboBoxRolActionPerformed(evt);
            }
        });
        JPanelUsuario.add(JComboBoxRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 210, -1));

        JTableAreaUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "No.", "Nombre Completo", "Usuario", "Contraseña", "Fecha Nacim.", "Rol"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JTableAreaUsuario.getTableHeader().setReorderingAllowed(false);
        JTableAreaUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTableAreaUsuarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTableAreaUsuario);

        JPanelUsuario.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 630, 470));

        JButtonGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenproducto/Guardar.png"))); // NOI18N
        JButtonGuardar.setBorderPainted(false);
        JButtonGuardar.setContentAreaFilled(false);
        JButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonGuardarActionPerformed(evt);
            }
        });
        JPanelUsuario.add(JButtonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 230, 70));

        JButtonEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenproducto/Eliminar.png"))); // NOI18N
        JButtonEliminar.setBorderPainted(false);
        JButtonEliminar.setContentAreaFilled(false);
        JButtonEliminar.setFocusPainted(false);
        JButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonEliminarActionPerformed(evt);
            }
        });
        JPanelUsuario.add(JButtonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 230, -1));

        JButtonLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenproducto/Limpiar.png"))); // NOI18N
        JButtonLimpiar.setBorderPainted(false);
        JButtonLimpiar.setContentAreaFilled(false);
        JButtonLimpiar.setFocusPainted(false);
        JButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonLimpiarActionPerformed(evt);
            }
        });
        JPanelUsuario.add(JButtonLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 230, -1));

        JTabbedPane.addTab("Usuario", JPanelUsuario);

        JPanelPrivilegio.setBackground(new java.awt.Color(236, 236, 236));
        JPanelPrivilegio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLTituloBanner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenprivi/Privilegios.png"))); // NOI18N
        JPanelPrivilegio.add(JLTituloBanner, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, -1, -1));

        JLBanner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenprivi/BannerConfig.png"))); // NOI18N
        JPanelPrivilegio.add(JLBanner, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        JPanelPrivilegio.add(JCheckBoxApartadoAbono, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        JLApartado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenprivi/Apartado y Abonos.png"))); // NOI18N
        JPanelPrivilegio.add(JLApartado, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, -1));
        JPanelPrivilegio.add(JCheckBoxCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        JLCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenprivi/Compras.png"))); // NOI18N
        JPanelPrivilegio.add(JLCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, -1));
        JPanelPrivilegio.add(JCheckBoxConfiguracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        JLConfig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenprivi/Configuración.png"))); // NOI18N
        JPanelPrivilegio.add(JLConfig, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, -1));
        JPanelPrivilegio.add(JCheckBoxCorteCaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        JLCorte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenprivi/Corte de Caja.png"))); // NOI18N
        JPanelPrivilegio.add(JLCorte, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, -1, -1));
        JPanelPrivilegio.add(JCheckBoxInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, -1));

        JLInvent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenprivi/Inventario.png"))); // NOI18N
        JPanelPrivilegio.add(JLInvent, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, -1, -1));
        JPanelPrivilegio.add(JCheckBoxProveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, -1, -1));

        JLProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenprivi/Proveedores.png"))); // NOI18N
        JPanelPrivilegio.add(JLProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, -1, -1));
        JPanelPrivilegio.add(JCheckBoxRegCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, -1, -1));

        JLRegClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenprivi/Registrar Clientes.png"))); // NOI18N
        JPanelPrivilegio.add(JLRegClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, -1, -1));
        JPanelPrivilegio.add(JCheckBoxRegProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, -1, -1));

        JLRegProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenprivi/Registrar Productos.png"))); // NOI18N
        JPanelPrivilegio.add(JLRegProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, -1, -1));
        JPanelPrivilegio.add(JCheckBoxVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, -1, -1));

        JLVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenprivi/Ventas.png"))); // NOI18N
        JPanelPrivilegio.add(JLVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 460, -1, -1));
        JPanelPrivilegio.add(JCheckBoxApartadoAbono1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, -1, -1));

        JLApartado1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenprivi/Apartado y Abonos.png"))); // NOI18N
        JPanelPrivilegio.add(JLApartado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 140, -1, -1));
        JPanelPrivilegio.add(JCheckBoxCompras1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 180, -1, -1));

        JLCompras1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenprivi/Compras.png"))); // NOI18N
        JPanelPrivilegio.add(JLCompras1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 180, -1, -1));
        JPanelPrivilegio.add(JCheckBoxConfiguracion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 220, -1, -1));

        JLConfig1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenprivi/Configuración.png"))); // NOI18N
        JPanelPrivilegio.add(JLConfig1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 220, -1, -1));
        JPanelPrivilegio.add(JCheckBoxCorteCaja1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 260, -1, -1));

        JLCorte1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenprivi/Corte de Caja.png"))); // NOI18N
        JPanelPrivilegio.add(JLCorte1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 260, -1, -1));
        JPanelPrivilegio.add(JCheckBoxInventario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, -1, -1));

        JLInvent1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenprivi/Inventario.png"))); // NOI18N
        JPanelPrivilegio.add(JLInvent1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 300, -1, -1));
        JPanelPrivilegio.add(JCheckBoxProveedores1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 340, -1, -1));

        JLProveedor1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenprivi/Proveedores.png"))); // NOI18N
        JPanelPrivilegio.add(JLProveedor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 340, -1, -1));
        JPanelPrivilegio.add(JCheckBoxRegCliente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 380, -1, -1));

        JLRegClientes1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenprivi/Registrar Clientes.png"))); // NOI18N
        JPanelPrivilegio.add(JLRegClientes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 380, -1, -1));
        JPanelPrivilegio.add(JCheckBoxRegProducto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 420, -1, -1));

        JLRegProduct1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenprivi/Registrar Productos.png"))); // NOI18N
        JPanelPrivilegio.add(JLRegProduct1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 420, -1, -1));
        JPanelPrivilegio.add(JCheckBoxVentas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 460, -1, -1));

        JButtonGuardarA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenprivi/Guardar.png"))); // NOI18N
        JButtonGuardarA.setBorder(null);
        JButtonGuardarA.setBorderPainted(false);
        JButtonGuardarA.setContentAreaFilled(false);
        JButtonGuardarA.setFocusPainted(false);
        JButtonGuardarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonGuardarAActionPerformed(evt);
            }
        });
        JPanelPrivilegio.add(JButtonGuardarA, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 480, -1, 70));

        JButtonGuardarE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenprivi/Guardar.png"))); // NOI18N
        JButtonGuardarE.setBorder(null);
        JButtonGuardarE.setBorderPainted(false);
        JButtonGuardarE.setContentAreaFilled(false);
        JButtonGuardarE.setFocusPainted(false);
        JButtonGuardarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonGuardarEActionPerformed(evt);
            }
        });
        JPanelPrivilegio.add(JButtonGuardarE, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 480, -1, 70));

        JLVentas1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenprivi/Ventas.png"))); // NOI18N
        JPanelPrivilegio.add(JLVentas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 460, -1, -1));

        JLTituloCuadroADM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenprivi/Permisos Administrador.png"))); // NOI18N
        JPanelPrivilegio.add(JLTituloCuadroADM, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, -1, -1));

        JLTituloCuadroEMP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenprivi/Permisos Empleado.png"))); // NOI18N
        JPanelPrivilegio.add(JLTituloCuadroEMP, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 110, -1, -1));

        JLCuadroAdm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenprivi/CuadroPermiso.png"))); // NOI18N
        JLCuadroAdm.setText("jLabel1");
        JPanelPrivilegio.add(JLCuadroAdm, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 430, 480));

        JLCuadroEmp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenprivi/CuadroPermiso.png"))); // NOI18N
        JLCuadroEmp.setText("jLabel1");
        JPanelPrivilegio.add(JLCuadroEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, 430, 480));

        JTabbedPane.addTab("Privilegio", JPanelPrivilegio);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        JTabbedPane.addTab("Otros", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JTabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JTabbedPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonGuardarActionPerformed
        // TODO add your handling code here:
        if ("".equals(JTextNomCompForm.getText().trim()) || "".equals(JTextUsuarioForm.getText().trim()) || "".equals(JTextContrasenaForm.getText().trim()) || "".equals(JTextConfirmarContraForm.getText().trim())) {

            JTextNomCompForm.setText("Campo Obligatorio!!!");
            JTextNomCompForm.setForeground(Color.red);
            JTextUsuarioForm.setText("Campo Obligatorio!!!");
            JTextUsuarioForm.setForeground(Color.red);
            JTextContrasenaForm.setText("Campo Obligatorio!!!");
            JTextContrasenaForm.setForeground(Color.red);
            JTextConfirmarContraForm.setText("Campo Obligatorio!!!");
            JTextConfirmarContraForm.setForeground(Color.red);
            JTextFechaNacimForm.setText("Campo Obligatorio!!!");
            JTextFechaNacimForm.setForeground(Color.red);

        } else if (opcionClick == true) {

            try {
                String sql = "UPDATE usuario\n"
                        + "SET nombre_usuario = '" + JTextNomCompForm.getText().trim() + "', "
                        + "usuario = '" + JTextUsuarioForm.getText().trim() + "' , "
                        + "contraseña = " + JTextConfirmarContraForm.getText().trim() + " , "
                        + "fecha = '" + JTextFechaNacimForm.getText().trim() + "' , "
                        + "rol_usuario = '" + JComboBoxRol.getSelectedItem().toString() + "' "
                        + "WHERE id_user = " + bus;
                Connection cn = Conexion.conectar();
                PreparedStatement ps = cn.prepareStatement(sql);
                ps.execute();
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(RegistrarProducto.class.getName()).log(Level.SEVERE, null, ex);
            }
            CargarDatosTabla();
            JOptionPane.showMessageDialog(null, "Registro Actualizado Correctamente");
            opcionClick = false;
        } else {

            if (JTextContrasenaForm.getText().trim().equals(JTextConfirmarContraForm.getText().trim())) {
                String nombre, user, pass, rol, fecha;
                nombre = JTextNomCompForm.getText().trim();
                user = JTextUsuarioForm.getText().trim();
                pass = JTextContrasenaForm.getText().trim();
                fecha = JTextFechaNacimForm.getText().trim();
                rol = String.valueOf(JComboBoxRol.getSelectedItem()).trim();

                try {
                    //Realiza la conexion a la Base de Datos desde la clase Conexion
                    Connection cn = Conexion.conectar();
                    Statement st = cn.createStatement();
                    st.addBatch("INSERT INTO usuario ( nombre_usuario, usuario, contraseña, fecha, rol_usuario)"
                            + "VALUES ('" + nombre + "','" + user + "','" + pass + "', '" + fecha + "', '" + rol + "')");
                    st.executeBatch();
                    CargarDatosTabla();

                } catch (SQLException e) {
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(RegistrarProducto.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                JTextContrasenaForm.setText("Entrada Invalida");
                JTextConfirmarContraForm.setText("Entrada Invalida");
            }

        }
    }//GEN-LAST:event_JButtonGuardarActionPerformed

    private void JButtonGuardarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonGuardarAActionPerformed
        // TODO add your handling code here:

        String AccesoCON = "PERMITIDO", AccesoNEG = "NEGADO";
        try {
            Connection cn = Conexion.conectar();
            Statement st = cn.createStatement();

            if (JCheckBoxApartadoAbono.isSelected()) {
                String sql = "UPDATE privilegio SET apartado='" + AccesoCON + "' WHERE id_privilegio=1";
                st.addBatch(sql);
            } else if (!JCheckBoxApartadoAbono.isSelected()) {
                String sql = "UPDATE privilegio SET apartado='" + AccesoNEG + "' WHERE id_privilegio=1";
                st.addBatch(sql);
            }
            if (JCheckBoxCompras.isSelected()) {
                String sql = "UPDATE privilegio SET compra='" + AccesoCON + "' WHERE id_privilegio=1";
                st.addBatch(sql);
            } else if (!JCheckBoxCompras.isSelected()) {
                String sql = "UPDATE privilegio SET compra='" + AccesoNEG + "' WHERE id_privilegio=1";
                st.addBatch(sql);
            }
            if (JCheckBoxConfiguracion.isSelected()) {
                String sql = "UPDATE privilegio SET configuracion='" + AccesoCON + "' WHERE id_privilegio=1";
                st.addBatch(sql);
            } else if (!JCheckBoxConfiguracion.isSelected()) {
                JCheckBoxConfiguracion.setSelected(true);
                //String sql = "UPDATE privilegio SET configuracion='" + AccesoNEG + "' WHERE id_privilegio=1";
                //st.addBatch(sql);
            }
            if (JCheckBoxCorteCaja.isSelected()) {
                String sql = "UPDATE privilegio SET corte='" + AccesoCON + "' WHERE id_privilegio=1";
                st.addBatch(sql);
            } else if (!JCheckBoxCorteCaja.isSelected()) {
                String sql = "UPDATE privilegio SET corte='" + AccesoNEG + "' WHERE id_privilegio=1";
                st.addBatch(sql);
            }
            if (JCheckBoxInventario.isSelected()) {
                String sql = "UPDATE privilegio SET inventario='" + AccesoCON + "' WHERE id_privilegio=1";
                st.addBatch(sql);
            } else if (!JCheckBoxInventario.isSelected()) {
                String sql = "UPDATE privilegio SET inventario='" + AccesoNEG + "' WHERE id_privilegio=1";
                st.addBatch(sql);
            }
            if (JCheckBoxProveedores.isSelected()) {
                String sql = "UPDATE privilegio SET proveedor='" + AccesoCON + "' WHERE id_privilegio=1";
                st.addBatch(sql);
            } else if (!JCheckBoxProveedores.isSelected()) {
                String sql = "UPDATE privilegio SET proveedor='" + AccesoNEG + "' WHERE id_privilegio=1";
                st.addBatch(sql);
            }
            if (JCheckBoxRegCliente.isSelected()) {
                String sql = "UPDATE privilegio SET registrarcliente='" + AccesoCON + "' WHERE id_privilegio=1";
                st.addBatch(sql);
            } else if (!JCheckBoxRegCliente.isSelected()) {
                String sql = "UPDATE privilegio SET registrarcliente='" + AccesoNEG + "' WHERE id_privilegio=1";
                st.addBatch(sql);
            }
            if (JCheckBoxRegProducto.isSelected()) {
                String sql = "UPDATE privilegio SET registrarproducto='" + AccesoCON + "' WHERE id_privilegio=1";
                st.addBatch(sql);
            } else if (!JCheckBoxRegProducto.isSelected()) {
                String sql = "UPDATE privilegio SET registrarproducto='" + AccesoNEG + "' WHERE id_privilegio=1";
                st.addBatch(sql);
            }
            if (JCheckBoxVentas.isSelected()) {
                String sql = "UPDATE privilegio SET venta='" + AccesoCON + "' WHERE id_privilegio=1";
                st.addBatch(sql);
            } else if (!JCheckBoxVentas.isSelected()) {
                String sql = "UPDATE privilegio SET venta='" + AccesoNEG + "' WHERE id_privilegio=1";
                st.addBatch(sql);
            }
            st.executeBatch();
            JOptionPane.showMessageDialog(null, "Guardado Correctamente!!");
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(RegistrarProducto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_JButtonGuardarAActionPerformed

    private void JButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonLimpiarActionPerformed
        // TODO add your handling code here:
        JTextNomCompForm.setText("");
        JTextNomCompForm.setForeground(Color.black);
        JTextUsuarioForm.setText("");
        JTextUsuarioForm.setForeground(Color.black);
        JTextContrasenaForm.setText("");
        JTextContrasenaForm.setForeground(Color.black);
        JTextConfirmarContraForm.setText("");
        JTextConfirmarContraForm.setForeground(Color.black);
        JTextFechaNacimForm.setText("");
        JTextFechaNacimForm.setForeground(Color.black);
    }//GEN-LAST:event_JButtonLimpiarActionPerformed

    private void JButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonEliminarActionPerformed
        // TODO add your handling code here:
        if (opcionClick == true) {
            try {
                System.out.println(""+bus);
                Connection cn = Conexion.conectar();
                Statement st = cn.createStatement();
                st.addBatch("DELETE FROM usuario WHERE id_user = " + bus);
                st.executeBatch();
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(RegistrarProducto.class.getName()).log(Level.SEVERE, null, ex);
            }
            CargarDatosTabla();
        }

    }//GEN-LAST:event_JButtonEliminarActionPerformed

    private void JTableAreaUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTableAreaUsuarioMouseClicked
        // TODO add your handling code here:
        int fila = JTableAreaUsuario.getSelectedRow();
        bus = Integer.parseInt(JTableAreaUsuario.getValueAt(fila, 0).toString());

        opcionClick = true;
        try {

            Connection cn = Conexion.conectar();
            PreparedStatement ps = cn.prepareStatement("SELECT * FROM usuario");
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {

                JTextNomCompForm.setText(rs.getString("nombre_usuario"));
                JTextUsuarioForm.setText(rs.getString("usuario"));
                JTextContrasenaForm.setText(rs.getString("contraseña"));
                JTextConfirmarContraForm.setText(rs.getString("contraseña"));
                JTextFechaNacimForm.setText(rs.getString("fecha"));
                JComboBoxRol.setSelectedItem(rs.getString("rol_usuario"));
            }
        } catch (SQLException ex) {
            System.out.println(ex.toString());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(RegistrarProducto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_JTableAreaUsuarioMouseClicked

    private void JComboBoxRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JComboBoxRolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JComboBoxRolActionPerformed

    private void JButtonGuardarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonGuardarEActionPerformed
        // TODO add your handling code here:
        String AccesoCON = "PERMITIDO", AccesoNEG = "NEGADO";
        try {
            Connection cn = Conexion.conectar();
            Statement st = cn.createStatement();

            if (JCheckBoxApartadoAbono1.isSelected()) {
                String sql = "UPDATE privilegio SET apartado='" + AccesoCON + "' WHERE id_privilegio=2";
                st.addBatch(sql);
            } else if (!JCheckBoxApartadoAbono1.isSelected()) {
                String sql = "UPDATE privilegio SET apartado='" + AccesoNEG + "' WHERE id_privilegio=2";
                st.addBatch(sql);
            }
            if (JCheckBoxCompras1.isSelected()) {
                String sql = "UPDATE privilegio SET compra='" + AccesoCON + "' WHERE id_privilegio=2";
                st.addBatch(sql);
            } else if (!JCheckBoxCompras1.isSelected()) {
                String sql = "UPDATE privilegio SET compra='" + AccesoNEG + "' WHERE id_privilegio=2";
                st.addBatch(sql);
            }
            if (JCheckBoxConfiguracion1.isSelected()) {
                String sql = "UPDATE privilegio SET configuracion='" + AccesoCON + "' WHERE id_privilegio=2";
                st.addBatch(sql);
            } else if (!JCheckBoxConfiguracion1.isSelected()) {
                String sql = "UPDATE privilegio SET configuracion='" + AccesoNEG + "' WHERE id_privilegio=2";
                st.addBatch(sql);
            }
            if (JCheckBoxCorteCaja1.isSelected()) {
                String sql = "UPDATE privilegio SET corte='" + AccesoCON + "' WHERE id_privilegio=2";
                st.addBatch(sql);
            } else if (!JCheckBoxCorteCaja1.isSelected()) {
                String sql = "UPDATE privilegio SET corte='" + AccesoNEG + "' WHERE id_privilegio=2";
                st.addBatch(sql);
            }
            if (JCheckBoxInventario1.isSelected()) {
                String sql = "UPDATE privilegio SET inventario='" + AccesoCON + "' WHERE id_privilegio=2";
                st.addBatch(sql);
            } else if (!JCheckBoxInventario1.isSelected()) {
                String sql = "UPDATE privilegio SET inventario='" + AccesoNEG + "' WHERE id_privilegio=2";
                st.addBatch(sql);
            }
            if (JCheckBoxProveedores1.isSelected()) {
                String sql = "UPDATE privilegio SET proveedor='" + AccesoCON + "' WHERE id_privilegio=2";
                st.addBatch(sql);
            } else if (!JCheckBoxProveedores1.isSelected()) {
                String sql = "UPDATE privilegio SET proveedor='" + AccesoNEG + "' WHERE id_privilegio=2";
                st.addBatch(sql);
            }
            if (JCheckBoxRegCliente1.isSelected()) {
                String sql = "UPDATE privilegio SET registrarcliente='" + AccesoCON + "' WHERE id_privilegio=2";
                st.addBatch(sql);
            } else if (!JCheckBoxRegCliente1.isSelected()) {
                String sql = "UPDATE privilegio SET registrarcliente='" + AccesoNEG + "' WHERE id_privilegio=2";
                st.addBatch(sql);
            }
            if (JCheckBoxRegProducto1.isSelected()) {
                String sql = "UPDATE privilegio SET registrarproducto='" + AccesoCON + "' WHERE id_privilegio=2";
                st.addBatch(sql);
            } else if (!JCheckBoxRegProducto1.isSelected()) {
                String sql = "UPDATE privilegio SET registrarproducto='" + AccesoNEG + "' WHERE id_privilegio=2";
                st.addBatch(sql);
            }
            if (JCheckBoxVentas1.isSelected()) {
                String sql = "UPDATE privilegio SET venta='" + AccesoCON + "' WHERE id_privilegio=2";
                st.addBatch(sql);
            } else if (!JCheckBoxVentas1.isSelected()) {
                String sql = "UPDATE privilegio SET venta='" + AccesoNEG + "' WHERE id_privilegio=2";
                st.addBatch(sql);
            }
            st.executeBatch();
            JOptionPane.showMessageDialog(null, "Guardado Correctamente!!");
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(RegistrarProducto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_JButtonGuardarEActionPerformed

    private void JButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonSalirActionPerformed
        // TODO add your handling code here:
        new Menu().setVisible(true);
        dispose();
    }//GEN-LAST:event_JButtonSalirActionPerformed

    private void CargarDatosTabla() {
        try {
            DefaultTableModel modelo = new DefaultTableModel();
            modelo.addColumn("No.");
            modelo.addColumn("Nombre Completo");
            modelo.addColumn("Usuario");
            modelo.addColumn("Contraseña");
            modelo.addColumn("Fecha Nacim.");
            modelo.addColumn("Rol");

            JTableAreaUsuario.setModel(modelo);

            Connection cn = Conexion.conectar();
            Statement st = cn.createStatement();

            String sql = "SELECT * FROM usuario";

            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                Object[] filas = new Object[6];
                for (int i = 0; i < 6; i++) {
                    filas[i] = rs.getObject(i + 1);
                }
                modelo.addRow(filas);
            }

        } catch (SQLException ex) {
            System.err.println(ex.toString());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(RegistrarProducto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void SeleccionAdministrador() {
        String apartado = "", compra = "", config = "", corte = "", inventario = "", proveedor = "", regcliente = "", regproducto = "", venta = "";
        try {
            Connection cn = Conexion.conectar();
            Statement st = cn.createStatement();

            ResultSet rs = st.executeQuery("SELECT apartado, compra, configuracion, corte, inventario, proveedor, registrarcliente, registrarproducto, venta FROM privilegio WHERE id_privilegio=1");

            while (rs.next()) {
                apartado = rs.getString("apartado");
                compra = rs.getString("compra");
                config = rs.getString("configuracion");
                corte = rs.getString("corte");
                inventario = rs.getString("inventario");
                proveedor = rs.getString("proveedor");
                regcliente = rs.getString("registrarcliente");
                regproducto = rs.getString("registrarproducto");
                venta = rs.getString("venta");
            }

            if (apartado.equalsIgnoreCase("PERMITIDO")) {
                JCheckBoxApartadoAbono.setSelected(true);
            } else if (apartado.equalsIgnoreCase("NEGADO")) {
                JCheckBoxApartadoAbono.setSelected(false);
            }
            if (compra.equalsIgnoreCase("PERMITIDO")) {
                JCheckBoxCompras.setSelected(true);
            } else if (compra.equalsIgnoreCase("NEGADO")) {
                JCheckBoxCompras.setSelected(false);
            }
            if (config.equalsIgnoreCase("PERMITIDO")) {
                JCheckBoxConfiguracion.setSelected(true);
            } else if (config.equalsIgnoreCase("NEGADO")) {
                JCheckBoxConfiguracion.setSelected(false);
            }
            if (corte.equalsIgnoreCase("PERMITIDO")) {
                JCheckBoxCorteCaja.setSelected(true);
            } else if (corte.equalsIgnoreCase("NEGADO")) {
                JCheckBoxCorteCaja.setSelected(false);
            }
            if (inventario.equalsIgnoreCase("PERMITIDO")) {
                JCheckBoxInventario.setSelected(true);
            } else if (inventario.equalsIgnoreCase("NEGADO")) {
                JCheckBoxInventario.setSelected(false);
            }
            if (proveedor.equalsIgnoreCase("PERMITIDO")) {
                JCheckBoxProveedores.setSelected(true);
            } else if (proveedor.equalsIgnoreCase("NEGADO")) {
                JCheckBoxProveedores.setSelected(false);
            }
            if (regcliente.equalsIgnoreCase("PERMITIDO")) {
                JCheckBoxRegCliente.setSelected(true);
            } else if (regcliente.equalsIgnoreCase("NEGADO")) {
                JCheckBoxRegCliente.setSelected(false);
            }
            if (regproducto.equalsIgnoreCase("PERMITIDO")) {
                JCheckBoxRegProducto.setSelected(true);
            } else if (regproducto.equalsIgnoreCase("NEGADO")) {
                JCheckBoxRegProducto.setSelected(false);
            }
            if (venta.equalsIgnoreCase("PERMITIDO")) {
                JCheckBoxVentas.setSelected(true);
            } else if (venta.equalsIgnoreCase("NEGADO")) {
                JCheckBoxVentas.setSelected(false);
            }
        } catch (ClassNotFoundException | SQLException e) {
        }
    }

    public void SeleccionEmpleado() {
        String apartado = "", compra = "", config = "", corte = "", inventario = "", proveedor = "", regcliente = "", regproducto = "", venta = "";
        try {
            Connection cn = Conexion.conectar();
            Statement st = cn.createStatement();

            ResultSet rs = st.executeQuery("SELECT apartado, compra, configuracion, corte, inventario, proveedor, registrarcliente, registrarproducto, venta FROM privilegio WHERE id_privilegio=2");

            while (rs.next()) {
                apartado = rs.getString("apartado");
                compra = rs.getString("compra");
                config = rs.getString("configuracion");
                corte = rs.getString("corte");
                inventario = rs.getString("inventario");
                proveedor = rs.getString("proveedor");
                regcliente = rs.getString("registrarcliente");
                regproducto = rs.getString("registrarproducto");
                venta = rs.getString("venta");
            }

            if (apartado.equalsIgnoreCase("PERMITIDO")) {
                JCheckBoxApartadoAbono1.setSelected(true);
            } else if (apartado.equalsIgnoreCase("NEGADO")) {
                JCheckBoxApartadoAbono1.setSelected(false);
            }
            if (compra.equalsIgnoreCase("PERMITIDO")) {
                JCheckBoxCompras1.setSelected(true);
            } else if (compra.equalsIgnoreCase("NEGADO")) {
                JCheckBoxCompras1.setSelected(false);
            }
            if (config.equalsIgnoreCase("PERMITIDO")) {
                JCheckBoxConfiguracion1.setSelected(true);
            } else if (config.equalsIgnoreCase("NEGADO")) {
                JCheckBoxConfiguracion1.setSelected(false);
            }
            if (corte.equalsIgnoreCase("PERMITIDO")) {
                JCheckBoxCorteCaja1.setSelected(true);
            } else if (corte.equalsIgnoreCase("NEGADO")) {
                JCheckBoxCorteCaja1.setSelected(false);
            }
            if (inventario.equalsIgnoreCase("PERMITIDO")) {
                JCheckBoxInventario1.setSelected(true);
            } else if (inventario.equalsIgnoreCase("NEGADO")) {
                JCheckBoxInventario1.setSelected(false);
            }
            if (proveedor.equalsIgnoreCase("PERMITIDO")) {
                JCheckBoxProveedores1.setSelected(true);
            } else if (proveedor.equalsIgnoreCase("NEGADO")) {
                JCheckBoxProveedores1.setSelected(false);
            }
            if (regcliente.equalsIgnoreCase("PERMITIDO")) {
                JCheckBoxRegCliente1.setSelected(true);
            } else if (regcliente.equalsIgnoreCase("NEGADO")) {
                JCheckBoxRegCliente1.setSelected(false);
            }
            if (regproducto.equalsIgnoreCase("PERMITIDO")) {
                JCheckBoxRegProducto1.setSelected(true);
            } else if (regproducto.equalsIgnoreCase("NEGADO")) {
                JCheckBoxRegProducto1.setSelected(false);
            }
            if (venta.equalsIgnoreCase("PERMITIDO")) {
                JCheckBoxVentas1.setSelected(true);
            } else if (venta.equalsIgnoreCase("NEGADO")) {
                JCheckBoxVentas1.setSelected(false);
            }
        } catch (ClassNotFoundException | SQLException e) {
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Configuracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Configuracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Configuracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Configuracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Configuracion().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButtonEliminar;
    private javax.swing.JButton JButtonGuardar;
    private javax.swing.JButton JButtonGuardarA;
    private javax.swing.JButton JButtonGuardarE;
    private javax.swing.JButton JButtonLimpiar;
    private javax.swing.JButton JButtonSalir;
    public javax.swing.JCheckBox JCheckBoxApartadoAbono;
    private javax.swing.JCheckBox JCheckBoxApartadoAbono1;
    public javax.swing.JCheckBox JCheckBoxCompras;
    private javax.swing.JCheckBox JCheckBoxCompras1;
    private javax.swing.JCheckBox JCheckBoxConfiguracion;
    private javax.swing.JCheckBox JCheckBoxConfiguracion1;
    private javax.swing.JCheckBox JCheckBoxCorteCaja;
    private javax.swing.JCheckBox JCheckBoxCorteCaja1;
    private javax.swing.JCheckBox JCheckBoxInventario;
    private javax.swing.JCheckBox JCheckBoxInventario1;
    private javax.swing.JCheckBox JCheckBoxProveedores;
    private javax.swing.JCheckBox JCheckBoxProveedores1;
    public javax.swing.JCheckBox JCheckBoxRegCliente;
    private javax.swing.JCheckBox JCheckBoxRegCliente1;
    private javax.swing.JCheckBox JCheckBoxRegProducto;
    private javax.swing.JCheckBox JCheckBoxRegProducto1;
    private javax.swing.JCheckBox JCheckBoxVentas;
    private javax.swing.JCheckBox JCheckBoxVentas1;
    private javax.swing.JComboBox<String> JComboBoxRol;
    private javax.swing.JLabel JLApartado;
    private javax.swing.JLabel JLApartado1;
    private javax.swing.JLabel JLBanner;
    private javax.swing.JLabel JLCompras;
    private javax.swing.JLabel JLCompras1;
    private javax.swing.JLabel JLConfig;
    private javax.swing.JLabel JLConfig1;
    private javax.swing.JLabel JLConfirmarContra;
    private javax.swing.JLabel JLConfirmarContraForm;
    private javax.swing.JLabel JLContrasena;
    private javax.swing.JLabel JLContrasenaForm;
    private javax.swing.JLabel JLCorte;
    private javax.swing.JLabel JLCorte1;
    private javax.swing.JLabel JLCuadroAdm;
    private javax.swing.JLabel JLCuadroEmp;
    private javax.swing.JLabel JLFechaNacimForm;
    private javax.swing.JLabel JLFechaNacimiento;
    private javax.swing.JLabel JLInvent;
    private javax.swing.JLabel JLInvent1;
    private javax.swing.JLabel JLNomCompForm;
    private javax.swing.JLabel JLNombreCompleto;
    private javax.swing.JLabel JLProveedor;
    private javax.swing.JLabel JLProveedor1;
    private javax.swing.JLabel JLRegClientes;
    private javax.swing.JLabel JLRegClientes1;
    private javax.swing.JLabel JLRegProduct;
    private javax.swing.JLabel JLRegProduct1;
    private javax.swing.JLabel JLRol;
    private javax.swing.JLabel JLTituloBanner;
    private javax.swing.JLabel JLTituloCuadroADM;
    private javax.swing.JLabel JLTituloCuadroEMP;
    private javax.swing.JLabel JLUsuario;
    private javax.swing.JLabel JLUsuarioForm;
    private javax.swing.JLabel JLVentas;
    private javax.swing.JLabel JLVentas1;
    private javax.swing.JLabel JLabelBanner;
    private javax.swing.JLabel JLabelTitulo;
    private javax.swing.JPanel JPanelPrivilegio;
    private javax.swing.JPanel JPanelUsuario;
    private javax.swing.JTabbedPane JTabbedPane;
    private javax.swing.JTable JTableAreaUsuario;
    private javax.swing.JTextField JTextConfirmarContraForm;
    private javax.swing.JTextField JTextContrasenaForm;
    private javax.swing.JTextField JTextFechaNacimForm;
    private javax.swing.JTextField JTextNomCompForm;
    private javax.swing.JTextField JTextUsuarioForm;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
