/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import clases.Conexion;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Misael Villar Julian
 */
public class Recuperacion extends javax.swing.JFrame {

    /**
     * Creates new form Recuperacion
     */
    public Recuperacion() {
        initComponents();
        
        setTitle("Recuperación");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Buscar = new javax.swing.JButton();
        JLResultado = new javax.swing.JLabel();
        JLResultadoForm1 = new javax.swing.JLabel();
        JTFResultadoForm1 = new javax.swing.JTextField();
        JLResultadoForm = new javax.swing.JLabel();
        JTFResultadoForm = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        JLFechaAño = new javax.swing.JLabel();
        JLFechaAñoForm = new javax.swing.JLabel();
        JTFFechaAñoForm = new javax.swing.JTextField();
        JLFechaMes1 = new javax.swing.JLabel();
        JLFechaMesForm1 = new javax.swing.JLabel();
        JTFFechaMesForm1 = new javax.swing.JTextField();
        JLFechaDia = new javax.swing.JLabel();
        JLFechaDiaForm = new javax.swing.JLabel();
        JTFFechaDiaForm = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 250));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(236, 236, 236));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Buscar.setText("Buscar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });
        jPanel1.add(Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, -1, -1));

        JLResultado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JLResultado.setForeground(new java.awt.Color(0, 0, 0));
        JLResultado.setText("Resultado:");
        jPanel1.add(JLResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, -1, -1));

        JLResultadoForm1.setBackground(new java.awt.Color(236, 236, 236));
        JLResultadoForm1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagencompra/FechaInicialCampo.png"))); // NOI18N
        jPanel1.add(JLResultadoForm1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, -1, 20));

        JTFResultadoForm1.setBackground(new java.awt.Color(236, 236, 236));
        JTFResultadoForm1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        JTFResultadoForm1.setBorder(null);
        JTFResultadoForm1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTFResultadoForm1KeyTyped(evt);
            }
        });
        jPanel1.add(JTFResultadoForm1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 90, 20));

        JLResultadoForm.setBackground(new java.awt.Color(236, 236, 236));
        JLResultadoForm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagencompra/FechaInicialCampo.png"))); // NOI18N
        jPanel1.add(JLResultadoForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, -1, 20));

        JTFResultadoForm.setBackground(new java.awt.Color(236, 236, 236));
        JTFResultadoForm.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        JTFResultadoForm.setBorder(null);
        JTFResultadoForm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTFResultadoFormKeyTyped(evt);
            }
        });
        jPanel1.add(JTFResultadoForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 90, 20));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Introduzca Su Fecha de Nacimiento.");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        JLFechaAño.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JLFechaAño.setForeground(new java.awt.Color(0, 0, 0));
        JLFechaAño.setText("Año:");
        jPanel1.add(JLFechaAño, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 40, 20));

        JLFechaAñoForm.setBackground(new java.awt.Color(236, 236, 236));
        JLFechaAñoForm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagencompra/FechaInicialCampo.png"))); // NOI18N
        jPanel1.add(JLFechaAñoForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, 20));

        JTFFechaAñoForm.setBackground(new java.awt.Color(236, 236, 236));
        JTFFechaAñoForm.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        JTFFechaAñoForm.setBorder(null);
        JTFFechaAñoForm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTFFechaAñoFormKeyTyped(evt);
            }
        });
        jPanel1.add(JTFFechaAñoForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 90, 20));

        JLFechaMes1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JLFechaMes1.setForeground(new java.awt.Color(0, 0, 0));
        JLFechaMes1.setText("Mes:");
        jPanel1.add(JLFechaMes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        JLFechaMesForm1.setBackground(new java.awt.Color(236, 236, 236));
        JLFechaMesForm1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagencompra/FechaInicialCampo.png"))); // NOI18N
        jPanel1.add(JLFechaMesForm1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, 20));

        JTFFechaMesForm1.setBackground(new java.awt.Color(236, 236, 236));
        JTFFechaMesForm1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        JTFFechaMesForm1.setBorder(null);
        JTFFechaMesForm1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTFFechaMesForm1KeyTyped(evt);
            }
        });
        jPanel1.add(JTFFechaMesForm1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 90, 20));

        JLFechaDia.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JLFechaDia.setForeground(new java.awt.Color(0, 0, 0));
        JLFechaDia.setText("Dia:");
        jPanel1.add(JLFechaDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        JLFechaDiaForm.setBackground(new java.awt.Color(236, 236, 236));
        JLFechaDiaForm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagencompra/FechaInicialCampo.png"))); // NOI18N
        jPanel1.add(JLFechaDiaForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, 20));

        JTFFechaDiaForm.setBackground(new java.awt.Color(236, 236, 236));
        JTFFechaDiaForm.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        JTFFechaDiaForm.setBorder(null);
        JTFFechaDiaForm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTFFechaDiaFormKeyTyped(evt);
            }
        });
        jPanel1.add(JTFFechaDiaForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 90, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTFFechaAñoFormKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTFFechaAñoFormKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
        if (c == '.' && JTFFechaAñoForm.getText().contains(".")) {
            evt.consume();
        }
    }//GEN-LAST:event_JTFFechaAñoFormKeyTyped

    private void JTFFechaMesForm1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTFFechaMesForm1KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
        if (c == '.' && JTFFechaMesForm1.getText().contains(".")) {
            evt.consume();
        }
    }//GEN-LAST:event_JTFFechaMesForm1KeyTyped

    private void JTFFechaDiaFormKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTFFechaDiaFormKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
        if (c == '.' && JTFFechaDiaForm.getText().contains(".")) {
            evt.consume();
        }
    }//GEN-LAST:event_JTFFechaDiaFormKeyTyped

    private void JTFResultadoFormKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTFResultadoFormKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFResultadoFormKeyTyped

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        // TODO add your handling code here:
        try {
            Connection cn = Conexion.conectar();
            Statement st = cn.createStatement();
            String fecha = JTFFechaAñoForm.getText().trim() + "-" + JTFFechaMesForm1.getText().trim() + "-" + JTFFechaDiaForm.getText().trim();

            ResultSet rs = st.executeQuery("SELECT usuario, contraseña FROM usuario WHERE fecha = '" + fecha + "';");

            while (rs.next()) {
                JTFResultadoForm.setText(rs.getString("usuario"));
                JTFResultadoForm1.setText(rs.getString("contraseña"));
            }

        } catch (ClassNotFoundException e) {
            System.err.println(e.toString());
        } catch (SQLException ex) {
            Logger.getLogger(Recuperacion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BuscarActionPerformed

    private void JTFResultadoForm1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTFResultadoForm1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFResultadoForm1KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Recuperacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Recuperacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Recuperacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Recuperacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Recuperacion().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buscar;
    private javax.swing.JLabel JLFechaAño;
    private javax.swing.JLabel JLFechaAñoForm;
    private javax.swing.JLabel JLFechaDia;
    private javax.swing.JLabel JLFechaDiaForm;
    private javax.swing.JLabel JLFechaMes1;
    private javax.swing.JLabel JLFechaMesForm1;
    private javax.swing.JLabel JLResultado;
    private javax.swing.JLabel JLResultadoForm;
    private javax.swing.JLabel JLResultadoForm1;
    private javax.swing.JTextField JTFFechaAñoForm;
    private javax.swing.JTextField JTFFechaDiaForm;
    private javax.swing.JTextField JTFFechaMesForm1;
    private javax.swing.JTextField JTFResultadoForm;
    private javax.swing.JTextField JTFResultadoForm1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
