/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import clases.Conexion;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDate;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Misael Villar Julian
 */
public class RegistrarClientes extends javax.swing.JFrame {

    boolean opcionClick = false;
    String bus = "";
    String fecharegistro = "";
    int codigo = 0;

    /**
     * Creates new form RegistrarClientes
     */
    public RegistrarClientes() {
        initComponents();

        setLocationRelativeTo(null);
        CargarDatosTabla();
        SistemaRegistro();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanelCliente = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        JButtonSalir = new javax.swing.JButton();
        JLPestana = new javax.swing.JLabel();
        JLTitulo = new javax.swing.JLabel();
        JLBanner = new javax.swing.JLabel();
        JLCodigoCliente = new javax.swing.JLabel();
        JLCodigoClienteForm = new javax.swing.JLabel();
        JTextCodigoClienteForm = new javax.swing.JTextField();
        JLNombreCompleto = new javax.swing.JLabel();
        JLNombreCompletoForm = new javax.swing.JLabel();
        JTextNombreForm = new javax.swing.JTextField();
        JLDireccion = new javax.swing.JLabel();
        JLDireccionForm = new javax.swing.JLabel();
        JTextDireccionForm = new javax.swing.JTextField();
        JLTelefono = new javax.swing.JLabel();
        JLTelefonoForm = new javax.swing.JLabel();
        JTextTelefonoForm = new javax.swing.JTextField();
        JButtonGuardar = new javax.swing.JButton();
        JButtonEliminar = new javax.swing.JButton();
        JButtonLimpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTableAreaClientes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        JPanelCliente.setBackground(new java.awt.Color(236, 236, 236));
        JPanelCliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagencliente/Cliente.png"))); // NOI18N
        JPanelCliente.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

        JButtonSalir.setText("Salir");
        JButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonSalirActionPerformed(evt);
            }
        });
        JPanelCliente.add(JButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 20, -1, -1));

        JLPestana.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagencliente/PestañaCliente.png"))); // NOI18N
        JPanelCliente.add(JLPestana, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        JLTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagencliente/Registro de Clientes.png"))); // NOI18N
        JPanelCliente.add(JLTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, -1, -1));

        JLBanner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagencliente/Banner.png"))); // NOI18N
        JPanelCliente.add(JLBanner, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        JLCodigoCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagencliente/Código de Cliente.png"))); // NOI18N
        JPanelCliente.add(JLCodigoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        JLCodigoClienteForm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagencliente/CodigoCliente.png"))); // NOI18N
        JPanelCliente.add(JLCodigoClienteForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        JTextCodigoClienteForm.setBackground(new java.awt.Color(236, 236, 236));
        JTextCodigoClienteForm.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        JTextCodigoClienteForm.setBorder(null);
        JPanelCliente.add(JTextCodigoClienteForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 190, -1));

        JLNombreCompleto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagencliente/Nombre Completo.png"))); // NOI18N
        JPanelCliente.add(JLNombreCompleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, 10));

        JLNombreCompletoForm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagencliente/NombreCompleto.png"))); // NOI18N
        JPanelCliente.add(JLNombreCompletoForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        JTextNombreForm.setBackground(new java.awt.Color(236, 236, 236));
        JTextNombreForm.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        JTextNombreForm.setBorder(null);
        JTextNombreForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextNombreFormActionPerformed(evt);
            }
        });
        JPanelCliente.add(JTextNombreForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 190, -1));

        JLDireccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagencliente/Dirección.png"))); // NOI18N
        JPanelCliente.add(JLDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        JLDireccionForm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagencliente/Direccion.png"))); // NOI18N
        JPanelCliente.add(JLDireccionForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        JTextDireccionForm.setBackground(new java.awt.Color(236, 236, 236));
        JTextDireccionForm.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        JTextDireccionForm.setBorder(null);
        JPanelCliente.add(JTextDireccionForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 190, -1));

        JLTelefono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagencliente/Telefono.png"))); // NOI18N
        JPanelCliente.add(JLTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        JLTelefonoForm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagencliente/Telefono-1.png"))); // NOI18N
        JPanelCliente.add(JLTelefonoForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        JTextTelefonoForm.setBackground(new java.awt.Color(236, 236, 236));
        JTextTelefonoForm.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        JTextTelefonoForm.setBorder(null);
        JTextTelefonoForm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTextTelefonoFormKeyTyped(evt);
            }
        });
        JPanelCliente.add(JTextTelefonoForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 190, -1));

        JButtonGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenproducto/Guardar.png"))); // NOI18N
        JButtonGuardar.setBorderPainted(false);
        JButtonGuardar.setContentAreaFilled(false);
        JButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonGuardarActionPerformed(evt);
            }
        });
        JPanelCliente.add(JButtonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 230, 70));

        JButtonEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenproducto/Eliminar.png"))); // NOI18N
        JButtonEliminar.setBorderPainted(false);
        JButtonEliminar.setContentAreaFilled(false);
        JButtonEliminar.setFocusPainted(false);
        JButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonEliminarActionPerformed(evt);
            }
        });
        JPanelCliente.add(JButtonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 230, -1));

        JButtonLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenproducto/Limpiar.png"))); // NOI18N
        JButtonLimpiar.setBorderPainted(false);
        JButtonLimpiar.setContentAreaFilled(false);
        JButtonLimpiar.setFocusPainted(false);
        JButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonLimpiarActionPerformed(evt);
            }
        });
        JPanelCliente.add(JButtonLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 230, -1));

        JTableAreaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre Completo", "Direccion", "Telefono"
            }
        ));
        JTableAreaClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTableAreaClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTableAreaClientes);

        JPanelCliente.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 630, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanelCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanelCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonGuardarActionPerformed
        // TODO add your handling code here:

        if ("".equals(JTextCodigoClienteForm.getText().trim()) || "".equals(JTextNombreForm.getText().trim()) || "".equals(JTextDireccionForm.getText().trim()) || "".equals(JTextTelefonoForm.getText().trim())) {
            JTextCodigoClienteForm.setText("Campo Obligatorio!!!");
            JTextCodigoClienteForm.setForeground(Color.red);
            JTextNombreForm.setText("Campo Obligatorio!!!");
            JTextNombreForm.setForeground(Color.red);
            JTextDireccionForm.setText("Campo Obligatorio!!!");
            JTextDireccionForm.setForeground(Color.red);
            JTextTelefonoForm.setText("Campo Obligatorio!!!");
            JTextTelefonoForm.setForeground(Color.red);
        } else if (opcionClick == true) {
            try {
                String sql = "UPDATE cliente\n"
                        + "SET nombre_cliente='" + JTextNombreForm.getText().trim() + "',"
                        + "direccion_cliente='" + JTextDireccionForm.getText().trim() + "',"
                        + "telefono_cliente=" + JTextTelefonoForm.getText().trim() + "\n"
                        + "WHERE id_cliente=" + bus;
                Connection cn = Conexion.conectar();
                PreparedStatement ps = cn.prepareStatement(sql);
                ps.execute();
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(RegistrarProducto.class.getName()).log(Level.SEVERE, null, ex);
            }
            CargarDatosTabla();
            JOptionPane.showMessageDialog(null, "Registro Actualizado Correctamente");
            opcionClick = false;
        } else {
            String codigo, nombre, direccion;
            long telefono;
            codigo = JTextCodigoClienteForm.getText().trim();
            nombre = JTextNombreForm.getText().trim();
            direccion = JTextDireccionForm.getText().trim();
            telefono = Long.parseLong(JTextTelefonoForm.getText().trim());

            if (JTextTelefonoForm.getText().trim().length() == 10) {
                try {
                    System.out.println("" + JTextTelefonoForm.getText().trim().length());
                    //Realiza la conexion a la Base de Datos desde la clase Conexion
                    Connection cn = Conexion.conectar();
                    Statement st = cn.createStatement();
                    st.addBatch("INSERT INTO cliente (id_cliente, nombre_cliente, direccion_cliente, telefono_cliente)"
                            + "VALUES ('" + codigo + "','" + nombre + "','" + direccion + "'," + telefono + ");");
                    st.executeBatch();

                    DefaultTableModel modelo = new DefaultTableModel();
                    JTableAreaClientes.setModel(modelo);
                    Object[] Nuevafila = {codigo, nombre, direccion, telefono};
                    modelo.addRow(Nuevafila);

                    CargarDatosTabla();

                } catch (SQLException e) {
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(RegistrarProducto.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                JTextTelefonoForm.setText("Entrada Invalida!!");
            }
        }
    }//GEN-LAST:event_JButtonGuardarActionPerformed

    private void JTextNombreFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextNombreFormActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextNombreFormActionPerformed

    private void JButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonSalirActionPerformed
        // TODO add your handling code here:
        dispose();
        new Menu().setVisible(true);
    }//GEN-LAST:event_JButtonSalirActionPerformed

    private void JButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonLimpiarActionPerformed
        // TODO add your handling code here:
        JTextCodigoClienteForm.setText("");
        JTextCodigoClienteForm.setForeground(Color.black);
        JTextNombreForm.setText("");
        JTextNombreForm.setForeground(Color.black);
        JTextDireccionForm.setText("");
        JTextDireccionForm.setForeground(Color.black);
        JTextTelefonoForm.setText("");
        JTextTelefonoForm.setForeground(Color.black);
    }//GEN-LAST:event_JButtonLimpiarActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_formMouseClicked

    private void JButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonEliminarActionPerformed
        // TODO add your handling code here:
        if (opcionClick == true) {
            try {
                String sql = " DELETE FROM cliente WHERE id_cliente='" + bus + "'";
                Connection cn = Conexion.conectar();
                PreparedStatement ps = cn.prepareStatement(sql);
                ps.execute();
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(RegistrarProducto.class.getName()).log(Level.SEVERE, null, ex);
            }
            CargarDatosTabla();
            opcionClick = false;
        }

    }//GEN-LAST:event_JButtonEliminarActionPerformed

    private void JTableAreaClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTableAreaClientesMouseClicked
        // TODO add your handling code here:
        int fila = JTableAreaClientes.getSelectedRow();
        bus = String.valueOf(JTableAreaClientes.getValueAt(fila, 0));
        opcionClick = true;
        try {

            Connection cn = Conexion.conectar();

            PreparedStatement ps = cn.prepareStatement("SELECT * FROM cliente WHERE id_cliente='" + bus + "'");
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                JTextCodigoClienteForm.setText(rs.getString("id_cliente"));
                JTextNombreForm.setText(rs.getString("nombre_cliente"));
                JTextDireccionForm.setText(rs.getString("direccion_cliente"));
                JTextTelefonoForm.setText(rs.getString("telefono_cliente"));
            }
        } catch (SQLException ex) {
            System.out.println(ex.toString());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(RegistrarProducto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_JTableAreaClientesMouseClicked

    private void JTextTelefonoFormKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTextTelefonoFormKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
        if (c == '.' && JTextTelefonoForm.getText().contains(".")) {
            evt.consume();
        }
    }//GEN-LAST:event_JTextTelefonoFormKeyTyped

    private void CargarDatosTabla() {
        try {
            DefaultTableModel modelo = new DefaultTableModel();
            modelo.addColumn("Codigo");
            modelo.addColumn("Nombre Completo");
            modelo.addColumn("Direccion");
            modelo.addColumn("Telefono");

            JTableAreaClientes.setModel(modelo);

            Connection cn = Conexion.conectar();
            Statement st = cn.createStatement();

            String sql = "SELECT * FROM cliente";

            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                Object[] filas = new Object[4];
                for (int i = 0; i < 4; i++) {
                    filas[i] = rs.getObject(i + 1);
                }
                modelo.addRow(filas);
            }

        } catch (SQLException ex) {
            System.err.println(ex.toString());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(RegistrarProducto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void SistemaRegistro() {
        FechaActual();
        GeneradorCodigo();
        String y, m, d;
        String nombrereg = "CLIENTE";
        y = fecharegistro.substring(0, 4);
        m = fecharegistro.substring(5, 7);
        d = fecharegistro.substring(8, 10);
        nombrereg = nombrereg + y + m + d;
        JTextCodigoClienteForm.setText(nombrereg.concat(String.valueOf(codigo)));
    }
    private void GeneradorCodigo() {
        Random rand = new Random();
        int rango = 10000000;
        codigo = rand.nextInt(rango);

    }
    private void FechaActual() {
        LocalDate fechaactual = LocalDate.now();
        fecharegistro = String.valueOf(fechaactual);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new RegistrarClientes().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButtonEliminar;
    private javax.swing.JButton JButtonGuardar;
    private javax.swing.JButton JButtonLimpiar;
    private javax.swing.JButton JButtonSalir;
    private javax.swing.JLabel JLBanner;
    private javax.swing.JLabel JLCodigoCliente;
    private javax.swing.JLabel JLCodigoClienteForm;
    private javax.swing.JLabel JLDireccion;
    private javax.swing.JLabel JLDireccionForm;
    private javax.swing.JLabel JLNombreCompleto;
    private javax.swing.JLabel JLNombreCompletoForm;
    private javax.swing.JLabel JLPestana;
    private javax.swing.JLabel JLTelefono;
    private javax.swing.JLabel JLTelefonoForm;
    private javax.swing.JLabel JLTitulo;
    private javax.swing.JPanel JPanelCliente;
    private javax.swing.JTable JTableAreaClientes;
    private javax.swing.JTextField JTextCodigoClienteForm;
    private javax.swing.JTextField JTextDireccionForm;
    private javax.swing.JTextField JTextNombreForm;
    private javax.swing.JTextField JTextTelefonoForm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
